services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pererecos-stats-subathon
    network_mode: host
    env_file:
      - ./backend/.env
    restart: unless-stopped
    working_dir: /app
