"""Schema package - re-exports all models for backward compatibility"""

from typing import Literal

# PlatformType literal
PlatformType = Literal["twitch", "kick", "all"]

# Import order matters to avoid circular dependencies
# 1. Base models with no dependencies
from .emotes import (
    EmoteUsage,
    EmotePositionData,
    EmotePositionResponse,
    EmotePositionUserEntry,
    EmotePositionUsersResponse,
    TopEmotesResponse,
    EmoteSearchResult,
    EmoteLeastUsedEntry,
    EmoteLeastUsedResponse,
    EmoteRankingResponse,
    EmoteCreatorEntry,
    EmoteCreatorsResponse,
    EmoteDiversidadeEntry,
    EmoteDiversidadeResponse,
    EmoteContributor,
    EmotePeriodCounts,
    EmoteDetailResponse,
    EmoteWeatherEntry,
    EmoteWeatherResponse,
)

from .smoke import (
    SmokeLeaderboardEntry,
    SmokeDayPoint,
    SmokeBestDay,
    SmokeToday,
    SmokeFirstToday,
    SmokeStreakEntry,
    SmokeTimeResponse,
    UserSmokeStats,
)

from .leaderboards import (
    LeaderboardEntry,
    LeaderboardResponse,
    RisingStarEntry,
    RisingStarsResponse,
    HourLeaderEntry,
    HourLeadersResponse,
    WriterEntry,
    WritersResponse,
    DuasCarasEntry,
    DuasCarasResponse,
    ActiveChatter,
    ActiveChattersResponse,
    ChatActivityPoint,
    ChatActivityResponse,
    OverallActivityResponse,
    UniqueChattersResponse,
    NamedLeaderboardEntry,
    NamedLeaderboardResponse,
    PererecoesBreakdown,
    PererecoesEntry,
    PererecoesResponse,
    FolhinhaCommandEntry,
    FolhinhaCommandsResponse,
    FolhinhaTabEntry,
    FolhinhaTabResponse,
    FolhinhaTabAllResponse,
)

# 2. User models that depend on above
from .user import (
    RecentMessage,
    HourlyActivity,
    RivalInfo,
    ReplyTarget,
    FavoriteHour,
    UserRankings,
    UserEmotePosition,
    UserStats,
    UserSearchResult,
    UserCoreResponse,
    UserActivityResponse,
    UserRankingsOnlyResponse,
    UserSocialResponse,
    UserEmotesResponse,
    UserRecentResponse,
    UserSmokeOnlyResponse,
    FolhinhaPartner,
    UserFolhinhaStats,
    UserFolhinhaOnlyResponse,
    PastUsername,
    UsernameHistoryResponse,
    FeedbackRequest,
    FeedbackResponse,
    HealthResponse,
    UserComparisonResponse,
    RandomMessageItem,
    RandomMessageResponse,
)

# Resolve forward references after all imports
UserStats.model_rebuild()
UserRankings.model_rebuild()
UserEmotePosition.model_rebuild()
UserEmotesResponse.model_rebuild()
UserSmokeOnlyResponse.model_rebuild()
UserFolhinhaOnlyResponse.model_rebuild()

__all__ = [
    # Platform type
    "PlatformType",
    # User models
    "RecentMessage",
    "HourlyActivity",
    "RivalInfo",
    "ReplyTarget",
    "FavoriteHour",
    "UserRankings",
    "UserEmotePosition",
    "UserStats",
    "UserSearchResult",
    "UserCoreResponse",
    "UserActivityResponse",
    "UserRankingsOnlyResponse",
    "UserSocialResponse",
    "UserEmotesResponse",
    "UserRecentResponse",
    "UserSmokeOnlyResponse",
    "FolhinhaPartner",
    "UserFolhinhaStats",
    "UserFolhinhaOnlyResponse",
    "PastUsername",
    "UsernameHistoryResponse",
    "FeedbackRequest",
    "FeedbackResponse",
    "HealthResponse",
    "UserComparisonResponse",
    "RandomMessageItem",
    "RandomMessageResponse",
    # Leaderboard models
    "LeaderboardEntry",
    "LeaderboardResponse",
    "RisingStarEntry",
    "RisingStarsResponse",
    "HourLeaderEntry",
    "HourLeadersResponse",
    "WriterEntry",
    "WritersResponse",
    "DuasCarasEntry",
    "DuasCarasResponse",
    "ActiveChatter",
    "ActiveChattersResponse",
    "ChatActivityPoint",
    "ChatActivityResponse",
    "OverallActivityResponse",
    "UniqueChattersResponse",
    "NamedLeaderboardEntry",
    "NamedLeaderboardResponse",
    "PererecoesBreakdown",
    "PererecoesEntry",
    "PererecoesResponse",
    "FolhinhaCommandEntry",
    "FolhinhaCommandsResponse",
    "FolhinhaTabEntry",
    "FolhinhaTabResponse",
    "FolhinhaTabAllResponse",
    # Emote models
    "EmoteUsage",
    "EmotePositionData",
    "EmotePositionResponse",
    "EmotePositionUserEntry",
    "EmotePositionUsersResponse",
    "TopEmotesResponse",
    "EmoteSearchResult",
    "EmoteLeastUsedEntry",
    "EmoteLeastUsedResponse",
    "EmoteRankingResponse",
    "EmoteCreatorEntry",
    "EmoteCreatorsResponse",
    "EmoteDiversidadeEntry",
    "EmoteDiversidadeResponse",
    "EmoteContributor",
    "EmotePeriodCounts",
    "EmoteDetailResponse",
    "EmoteWeatherEntry",
    "EmoteWeatherResponse",
    # Smoke models
    "SmokeLeaderboardEntry",
    "SmokeDayPoint",
    "SmokeBestDay",
    "SmokeToday",
    "SmokeFirstToday",
    "SmokeStreakEntry",
    "SmokeTimeResponse",
    "UserSmokeStats",
]
