/** Late-bound cross-module callbacks to avoid circular init issues. */
export const hooks = {
  selectUser: null,
  navigateToEmote: null,
  navigateToSection: null,
  navigateToRanqueadaBoard: null,
  hideRanqueadaBoardView: null,
  updateNavActive: null,
  showGeneralView: null,
  loadSectionData: null,
  refreshSidebarContext: null,
  updatePeriodLabels: null,
  syncCustomDateInputs: null,
  renderExportNerdEmote: null,
  refreshEmoteNotes: null,
  renderTopEmotes: null,
  renderEmotePositionBar: null,
  renderMessageWithEmotes: null,
  searchUsersForAutocomplete: null,
  loadEmotesSection: null,
  loadEmotesCondensadasSection: null,
  loadRodaSection: null,
  loadTimerSection: null,
  loadRanqueadaSection: null,
  loadFolhinhaSection: null,
  loadCompararSection: null,
  loadCoreStats: null,
  loadChartStats: null,
  loadInitialData: null,
  fetchUserStats: null,
  fetch7TVEmotes: null,
  loadRandomNavEmoteIcon: null,
  renderSimpleRankList: null,
};
